sudo: false

language: python

cache:
  directories:
  - $HOME/.cache/pip

env:
  matrix:
    - DISTRIB="ubuntu" PYTHON_VERSION="3.6" COVERAGE="true"

git:
  depth: 3

branches:
  only:
  - master
  - develop

install:
  - echo '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
  - date +%Y-%m-%d\ %H:%M:%S
  - source ci_scripts/travis_install.sh
  - echo '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
  - date +%Y-%m-%d\ %H:%M:%S
  - pip install -r requirements.txt
  - echo '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
  - date +%Y-%m-%d\ %H:%M:%S
  - pip install pytest pytest-cov
  - echo '+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++'
  - date +%Y-%m-%d\ %H:%M:%S

script:
  - source ci_scripts/travis_test.sh

after_success:
  - source ci_scripts/travis_success.sh

notifications:
  email: false