sudo: false
language: python

env:
  matrix:
    - DISTRIB="ubuntu" PYTHON_VERSION="3.6" COVERAGE="true"

addons:
  apt:
    packages:
      - git
      - python-pip

python:
  - "3.6"

install:
  - source travis_install.sh
  - pip install pytest pytest-cov

script:
  - pytest -v --cov iterbox iterbox

after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi